services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - grafana
    networks:
      - domotica_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_compose
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - domotica_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=domotica
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - domotica_network


  tuya_broadcast_monitor:
    image: python:latest
    container_name: tuya_broadcast_monitor
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python tuya_brodcast_monitor.py"
    depends_on:
      - mariadb
    network_mode: host

  tuya_polling_monitor:
    image: python
    container_name: tuya_polling_monitor
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && apt-get update && apt-get install -y jq && bash tuya_local_monitor.sh"
    depends_on:
      - mariadb
    networks:
      - domotica_network

  termo_ariston:
    image: python:latest
    container_name: termo_ariston
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python termo_ariston.py"
    depends_on:
      - mariadb
    networks:
      - domotica_network

volumes:
  grafana_data:
  mariadb_data:

networks:
  domotica_network:
    driver: bridge
